# Dusty-shock tests to run on ozstar

[phantom]
path = "~/repos/phantom"
setup = "dustyshock"
system = "ifort"
version = "d9a5507f3fd97b5ed5acf4547f82449476b29091"
patches = [
    "~/repos/multigrain/code/patches/phantom-d9a5507f-multigrain_setup_shock.patch",
    "~/repos/multigrain/code/patches/phantom-d9a5507f-idustbound.patch",
    "~/repos/multigrain/code/patches/phantom-d9a5507f-printing.patch"
]
extra_make_flags = ["MAXP=10000000", "ISOTHERMAL=yes"]
hdf5_path = "/apps/skylake/software/mpi/intel/2016.2.181-gcc-6.4.0/openmpi/3.0.0/hdf5/1.10.1"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_64"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_64/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_64/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_128"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_256"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_256/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_256/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_3-nx_64"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_64/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_64/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_3-nx_128"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_128/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_128/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_3-nx_256"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_256/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_256/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_128-alpha_0"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128_alpha_0/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128_alpha_0/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_3-nx_128-alpha_0"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_128_alpha_0/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-nx_128_alpha_0/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_128-recon_off"
setup-file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-recon-off/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-recon-off/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_3-nx_128-recon_off"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-recon-off/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_3-recon-off/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_128-K_10"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128-K_10/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128-K_10/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"

[[runs]]
prefix = "dustyshock"
path = "/fred/oz015/dmentipl/runs/multigrain/dustyshock/N_1-nx_128-hfact_1.5"
setup_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128-hfact_1.5/dustyshock.setup"
in_file = "~/repos/multigrain/code/initial-conditions/dustyshock/N_1-nx_128-hfact_1.5/dustyshock.in"
job_script = "~/repos/multigrain/code/misc/dustyshock-slurm.sh"
