name: multigrain
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - black
  - bokeh
  - click
  - flake8
  - ipympl
  - ipython
  - jupyterlab
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - pydocstyle
  - pylint
  - scipy
  - pip:
    - git+https://github.com/dmentipl/phantom-build#0101e1a47b1a4ac24255a730e579a5ba54b53b8f
    - phantomconfig>=0.2.2
    - phantomsetup
    - plonk>=0.5.0
