name: multigrain
channels:
  - dmentipl
  - defaults
dependencies:
  - python>=3.7
  - ipython
  - matplotlib
  - numpy
  - plonk
  - pip
  - scipy
  - pip:
    - phantombuild>=0.1.3
    - phantomconfig>=0.2.1
