name: multigrain
channels:
  - conda-forge
dependencies:
  - python==3.7
  - click
  - matplotlib
  - numpy
  - pint
  - scipy
  # Dev
  - black
  - flake8
  - ipython
  - jupyterlab
  - pip
  - pydocstyle
  - pylint
  # Plonk
  - astropy
  - h5py
  - pandas
  - scikit-image>=0.16
  - pip:
    - phantombuild>=0.1.4
    - phantomconfig>=0.2.2
    - git+https://github.com/dmentipl/plonk.git@8cdc31a4d2af14ef48a687eda3926b9473e4b3b8
    - git+https://github.com/dmentipl/phantom-setup.git@b5bec6857ba9b0ad2ed856c223b64a1d56a52e9f
    # Plonk
    - KDEpy
