name: multigrain
channels:
  - conda-forge
dependencies:
  - python==3.7
  - astropy
  - black
  - bokeh
  - click
  - flake8
  - h5py
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pint
  - pip
  - pydocstyle
  - pylint
  - scikit-image>=0.16
  - scipy
  - pip:
    - phantombuild>=0.1.4
    - phantomconfig>=0.2.2
    - git+https://github.com/dmentipl/phantom-setup.git@42dfefe619ee78ebad0e1ebbf9f657d926a0004e
    - KDEpy
    - plonk>=0.2.1
