name: multigrain
channels:
  - dmentipl
  - conda-forge
dependencies:
  - python==3.7
  - click
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - plonk>=0.2.0
  - pint
  - pip
  - scipy
  - pip:
    - phantombuild>=0.1.4
    - phantomconfig>=0.2.2
    - git+https://github.com/dmentipl/phantom-setup.git@b5bec6857ba9b0ad2ed856c223b64a1d56a52e9f
