name: multigrain
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - black
  - bokeh
  - flake8
  - ipympl
  - ipython
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - pydocstyle
  - pylint
  - scipy
  - pip:
    - phantombuild>=0.1.4
    - phantomconfig>=0.2.2
    - phantomsetup
    - git+https://github.com/dmentipl/plonk.git@666f5fc283058b5f7563ecef94d23da3e1fc4cf9
