name: multigrain
channels:
  - conda-forge
dependencies:
  - python=3.7
  - black
  - click
  - flake8
  - h5py
  - ipympl
  - ipython
  - jinja2
  - jupyterlab
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pint>=0.10.1
  - pip
  - pydocstyle
  - pylint
  - scipy
  - scikit-image>=0.16
  - tomlkit
  - tqdm
  - pip:
    - git+https://github.com/dmentipl/phantom-build#df974845a50327281f49ccb4364719d80c8366b5
    - git+https://github.com/dmentipl/phantom-config#8780bd7555ef914fd5e024cc147f4496c2e81867
    - git+https://github.com/dmentipl/plonk#2d6ae4a2cd3d346f810d91f32fcfa8a9e2276391
    - phantomsetup
