name: multigrain
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - black
  - click
  - flake8
  - ipympl
  - ipython
  - jupyterlab
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - pydocstyle
  - pylint
  - scipy
  - tqdm
  - pip:
    - git+https://github.com/dmentipl/phantom-build#474c3cd4e197aa037b6906738710b9197e4cc557
    - phantomconfig>=0.3.2
    - phantomsetup
    - plonk>=0.5.0
