name: multigrain
channels:
  - conda-forge
dependencies:
  - python==3.7
  - black
  - bokeh
  - click
  - flake8
  - ipython
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - plonk>=0.3.0
  - pydocstyle
  - pylint
  - scipy
  - pip:
    - phantombuild>=0.1.4
    - phantomconfig>=0.2.2
    - git+https://github.com/dmentipl/phantom-setup.git@0e0ef236f06a41fced8ea3e1ad6e531a095ae279
