name: multigrain
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - black
  - bokeh
  - flake8
  - ipympl
  - ipython
  - jupyterlab
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - pydocstyle
  - pylint
  - scipy
  - pip:
    - phantombuild>=0.1.4
    - phantomconfig>=0.2.2
    - phantomsetup
    - plonk>=0.5.0
