prefix = "dustybox"
length_unit = "au"
mass_unit = "solarm"
time_unit = "year"
ieos = 1
sound_speed = 1.0
box_boundary = [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5]
number_of_particles_gas = 50000
number_of_particles_dust = 10000
density_gas = 1.0
dust_to_gas_ratio = [0.01, 0.02, 0.03, 0.04, 0.05]
dust_method = "largegrains"
drag_method = "K_const"
K_drag = 1.0
grain_size = []
grain_density = 0.0
velocity_delta = 1.0
maximum_time = 0.1
number_of_dumps = 20
