prefix = "dustybox"
length_unit = 1.0
mass_unit = 1.0
time_unit = 1.0
ieos = 1
sound_speed = 1.0
box_boundary = [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5]
number_of_particles_gas = 50000
number_of_particles_dust = 10000
density_gas = 1.0e-13
dust_to_gas_ratio = [0.05, 0.05, 0.05, 0.05, 0.05]
dust_method = "largegrains"
drag_method = "Epstein/Stokes"
K_drag = 0.0
grain_size = [0.1, 0.316, 1.0, 3.16, 10.0]
grain_density = 0.5e-14
velocity_delta = 1.0
maximum_time = 0.1
number_of_dumps = 100
